### ISSUE TITLE
[].includes is not a function in node < 4.8

### ISSUE THREAD

**Issue by vertex** [mhipszki/eslint-formatter-summary#1]
```
$ node --version
v4.8.3
$ npx eslint -f node_modules/eslint-formatter-summary .
["rule","errors","warnings"].includes is not a function
```
![screen shot 2017-09-29 at 10 25 56 am](https://user-images.githubusercontent.com/59979/31027854-aa8903bc-a500-11e7-81c4-91d4da8f18af.png)

**Comment by mhipszki** [comment]
@vertex thanks for reporting this issue, let me fix it and release a new patch version

**Comment by mhipszki** [comment]
merged in fix by @vertex
