### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by jaydp17** [mhipszki/eslint-formatter-summary#7]
Hey @mhipszki, I can help you with adding [prettier](https://github.com/prettier/prettier).

What code styles would you like to have?
For example, I usually prefer
- line width 120
- single quotes
- trailing commas everywhere except function params

Also, would you like to check if all the files are properly formatted in Travis CI?

**Comment by mhipszki** [comment]
Hi @jaydp17 that'd be great and the CI check would also be nice to have. Let's just stick to the default config first, please raise a PR and I'll have a look 👍

**Comment by jaydp17** [comment]
Here's the PR https://github.com/mhipszki/eslint-formatter-summary/pull/8

**Comment by mhipszki** [comment]
@jaydp17 merged #8 many thanks for your contribution 👍
